### ISSUE TITLE
try and except out of loops

### ISSUE THREAD

**Issue by mariogmarq** [BixMoo-TzArc02/StudiesOrganizer#2]
Been looking for the code, and in menu1 the try and except blocks are out of a loop, this means that if for example I enter a letter where it ask me to enter a number it will prompt the error text but it won't let me enter the number again, just go to the next step.

This is how it is right now:
```python
 try:
        courseInput = int(input('Which year are you in? Insert a number: '))
    except ValueError:
        print ('Error: You did not enter a number. Please try again.')
```

And this how should be for making letting the user enter again the number
```python
while True:
	try:
		courseInput = int(input('Which year are you in? Insert a number: '))
		break
	except ValueError:
		print ('Error: You did not enter a number. Please try again.')
```

Hope that it helped

**Comment by BixMoo** [comment]
We really appreciate your correction. We'll change it asap :-)
